## Project :  Support Vector machine

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('c:\Users\Kishore\Desktop\Datasets\Advertising_data.csv')

In [3]:
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
X = dataset.iloc[:, [2, 3]]
y = dataset.iloc[:, 4]



In [5]:
dataset.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[ 0.77063564, -1.37090753],
       [-0.95681661, -0.74731782],
       [ 1.25048349, -1.37090753],
       [ 0.09884866,  1.09375655],
       [-0.28502962, -0.56914934],
       [-1.14875575,  0.49986159],
       [-1.05278618,  0.44047209],
       [-1.14875575,  0.3216931 ],
       [ 1.5383922 ,  1.15314605],
       [-0.95681661, -0.3018966 ],
       [ 2.01824005, -0.80670732],
       [ 0.09884866, -0.80670732],
       [ 2.01824005,  0.55925109],
       [ 0.86660521, -0.53945459],
       [-0.28502962,  0.11382987],
       [-0.86084704,  0.17321936],
       [ 0.2907878 , -0.27220186],
       [-0.28502962, -0.27220186],
       [ 0.38675737,  2.37063071],
       [ 1.73033134,  1.89551474],
       [ 0.19481823, -0.24250711],
       [ 1.05854435, -1.22243379],
       [-0.18906005, -0.56914934],
       [ 1.44242263,  0.3810826 ],
       [-0.28502962, -1.40060228],
       [ 0.96257478, -1.07396005],
       [ 1.82630091, -0.27220186],
       [-0.28502962,  0.55925109],
       [-1.14875575,

In [9]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
y_pred = classifier.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)



In [12]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [13]:
accuracy

0.84999999999999998

In [14]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]


In [15]:
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)



In [16]:
grid_search = grid_search.fit(X_train, y_train)


In [17]:
accuracy = grid_search.best_score_


In [18]:
accuracy

0.91000000000000003

In [19]:
grid_search.best_params_

{'C': 10, 'gamma': 0.3, 'kernel': 'rbf'}

In [20]:
grid_search.best_estimator_

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.3, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
classifier = SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.3, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)
classifier.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.3, kernel='rbf',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
y_pred = classifier.predict(X_test)

In [23]:
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [24]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[61,  5],
       [ 2, 32]], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [26]:
accuracy

0.93000000000000005